fix default RHODS label to use strings
This was causing the following error when creating new OpenShift
projects:

coldfront_plugin_cloud.openshift.ApiException: 400: {"msg":"Unexpected
  response from OpenShift API: Project in version \"v1\" cannot be
    handled as a Project: json: cannot unmarshal bool into Go struct
    field ObjectMeta.metadata.labels of type string"}

related: #115